#如果报错误java.nio.charset.MalformedInputException: Input length = 1时表示编码错误，可以把中文全部去掉即可
#当前项目部署的端口
server:
  port: 8763

#配置服务中心的位置，并把自己注册进去
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#当前项目名字
spring:
  application:
    name: service-client

